export const questions = [
    { id: 'companyName', question: "What's the full legal name of your startup?" },
    { id: 'foundingYear', question: "In which year was the startup incorporated?" },
    { id: 'founderBackground', question: "Can you tell me about the founders' relevant industry experience and any previous exits?" },
    { id: 'productDescription', question: "Could you provide a detailed description of your main product or service?" },
    { id: 'targetMarket', question: "What's your specific target market, and what's its estimated size in USD?" },
    { id: 'competitiveLandscape', question: "Who are your top 3 competitors and how do you differentiate from them?" },
    { id: 'revenueModel', question: "Can you explain your revenue model and pricing strategy?" },
    { id: 'financials', question: "What was your revenue, gross margin, and net profit/loss in the last fiscal year?" },
    { id: 'keyMetrics', question: "What are the top 3 KPIs you track, and what are their current values?" },
    { id: 'fundingHistory', question: "Can you provide details of all your funding rounds to date (date, amount, investors)?" },
    { id: 'burnRate', question: "What's your current monthly burn rate and runway?" },
    { id: 'intellectualProperty', question: "Do you have any patents, trademarks, or other IP? If so, please describe them." },
    { id: 'teamComposition', question: "Can you provide a breakdown of the team composition?" },
    { id: 'regulatoryCompliance', question: "Are there any specific regulatory requirements for your startup? If yes, what's your compliance status?" },
    { id: 'growthStrategy', question: "What's your growth strategy for the next 2-3 years?" },
  ];